### ISSUE TITLE
Error with serverload

### ISSUE THREAD

**Issue by ghost** [LyricLy/ASCII#106]
Hello, so i used serversave to save a server, and when i try to load it on another server, i get this error:
Beginning server load process...
Loading roles...
Loading categories...
Loading text channels...
Loading voice channels...
Ignoring exception in command serverload
Traceback (most recent call last):
  File "C:\Users\mattl\AppData\Roaming\Python\Python36\site-packages\discord\ext\commands\core.py", line 60, in wrapped
    ret = await coro(*args, **kwargs)
  File "C:\Users\mattl\Desktop\Developement\Discord\Discord-Selfbot-master\Discord-Selfbot-master\custom_cogs\serversave.py", line 303, in serverload
    await channel_obj.edit(name=channel["name"], topic=channel["topic"], category=category, reason="Loading saved server")
KeyError: 'topic'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\mattl\AppData\Roaming\Python\Python36\site-packages\discord\ext\commands\bot.py", line 876, in invoke
    await ctx.command.invoke(ctx)
  File "C:\Users\mattl\AppData\Roaming\Python\Python36\site-packages\discord\ext\commands\core.py", line 506, in invoke
    await injected(*ctx.args, **ctx.kwargs)
  File "C:\Users\mattl\AppData\Roaming\Python\Python36\site-packages\discord\ext\commands\core.py", line 69, in wrapped
    raise CommandInvokeError(e) from e
discord.ext.commands.errors.CommandInvokeError: Command raised an exception: KeyError: 'topic'

is there something i'm doing wrong?
also i'm aware it's an old project and it may be discord who changed how server worked or something.
anyway it would be really great if you could reply, thanks in advance!

**Comment by DeadBread76** [comment]
big bruh monument
